"""Initial baseline - all tables created

Revision ID: 2682d6bccfbd
Revises: 
Create Date: 2026-05-26 10:02:11.812302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2682d6bccfbd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_records', 'billing_cycle',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stores', 'owner_id',
               existing_type=sa.TEXT(),
               type_=app.models.base.GUID(),
               existing_nullable=True)
    op.create_index(op.f('ix_stores_owner_id'), 'stores', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'stores', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_index(op.f('ix_stores_owner_id'), table_name='stores')
    op.alter_column('stores', 'owner_id',
               existing_type=app.models.base.GUID(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('payment_records', 'billing_cycle',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'yearly'"),
               existing_nullable=False)
    # ### end Alembic commands ###
