"""add collection_pack models

Revision ID: 44d7e086d0e4
Revises: 2682d6bccfbd
Create Date: 2026-05-28 16:37:55.794736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44d7e086d0e4'
down_revision: Union[str, None] = '2682d6bccfbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_packs',
    sa.Column('name', sa.String(length=100), nullable=False, comment='套餐名称'),
    sa.Column('credit_amount', sa.Integer(), nullable=False, comment='包含积分数量（条）'),
    sa.Column('price', sa.Float(), nullable=False, comment='价格（元）'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='套餐描述'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('id', sa.String(36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_orders',
    sa.Column('user_id', sa.String(36), nullable=False, comment='用户ID'),
    sa.Column('pack_id', sa.String(36), nullable=False, comment='套餐ID'),
    sa.Column('amount', sa.Float(), nullable=False, comment='支付金额'),
    sa.Column('payment_method', sa.String(length=20), nullable=False, comment='支付方式: wechat/alipay'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending/success/failed'),
    sa.Column('transaction_id', sa.String(length=100), nullable=True, comment='交易流水号'),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True, comment='支付时间'),
    sa.Column('id', sa.String(36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['pack_id'], ['collection_packs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_orders_pack_id'), 'collection_orders', ['pack_id'], unique=False)
    op.create_index(op.f('ix_collection_orders_user_id'), 'collection_orders', ['user_id'], unique=False)
    op.create_table('user_collection_balances',
    sa.Column('user_id', sa.String(36), nullable=False, comment='用户ID'),
    sa.Column('balance', sa.Integer(), nullable=False, comment='当前剩余积分'),
    sa.Column('total_purchased', sa.Integer(), nullable=False, comment='累计购买积分'),
    sa.Column('id', sa.String(36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_collection_balances_user_id'), 'user_collection_balances', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_collection_balances_user_id'), table_name='user_collection_balances')
    op.drop_table('user_collection_balances')
    op.drop_index(op.f('ix_collection_orders_user_id'), table_name='collection_orders')
    op.drop_index(op.f('ix_collection_orders_pack_id'), table_name='collection_orders')
    op.drop_table('collection_orders')
    op.drop_table('collection_packs')
    # ### end Alembic commands ###